### ISSUE TITLE
Support for MacOS

### ISSUE THREAD

**Issue by pablovela5620** [openxrlab/xrprimer#45]
I'm getting the following error when trying to install xrprimer via pip. I'm guessing its to no official mac support and only IOS. Would love to see support for mac os!

```
This warning is for project developers.  Use -Wno-dev to suppress it.

      -- pybind11 v2.6.2
      -- Found PythonInterp: /Users/pablovela/miniforge3/envs/xrprimer-test/bin/python (found version "3.10.12")
      -- Found PythonLibs: /Users/pablovela/miniforge3/envs/xrprimer-test/lib/libpython3.10.dylib
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- Performing Test HAS_FLTO_THIN
      -- Performing Test HAS_FLTO_THIN - Success
      HEAD is now at 8710099 feat: add BUILD_SHARED_LIBS for build static library
      -- Build type specified as Release
      -- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
      -- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
      -- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
      -- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
      -- Performing Test COMPILER_HAS_DEPRECATED_ATTR
      -- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
      -- Found Python3: /Users/pablovela/miniforge3/envs/xrprimer-test/bin/python3.10 (found version "3.10.12") found components: Interpreter Development Development.Module Development.Embed
      -- Configuring incomplete, errors occurred!
      See also "/private/var/folders/tf/rbxr_mz11n19ph5s2tzkqr580000gn/T/pip-install-jagqhs5r/xrprimer_7b2766ed18604c2ebeee1d57c104dcf5/build/temp.macosx-11.0-arm64-cpython-310/CMakeFiles/CMakeOutput.log".
      See also "/private/var/folders/tf/rbxr_mz11n19ph5s2tzkqr580000gn/T/pip-install-jagqhs5r/xrprimer_7b2766ed18604c2ebeee1d57c104dcf5/build/temp.macosx-11.0-arm64-cpython-310/CMakeFiles/CMakeError.log".
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/tf/rbxr_mz11n19ph5s2tzkqr580000gn/T/pip-install-jagqhs5r/xrprimer_7b2766ed18604c2ebeee1d57c104dcf5/setup.py", line 279, in <module>
          setup(
        File "/Users/pablovela/miniforge3/envs/xrprimer-test/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/Users/pablovela/miniforge3/envs/xrprimer-test/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/Users/pablovela/miniforge3/envs/xrprimer-test/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/pablovela/miniforge3/envs/xrprimer-test/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/pablovela/miniforge3/envs/xrprimer-test/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/Users/pablovela/miniforge3/envs/xrprimer-test/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/pablovela/miniforge3/envs/xrprimer-test/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "/Users/pablovela/miniforge3/envs/xrprimer-test/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/pablovela/miniforge3/envs/xrprimer-test/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/Users/pablovela/miniforge3/envs/xrprimer-test/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/pablovela/miniforge3/envs/xrprimer-test/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/Users/pablovela/miniforge3/envs/xrprimer-test/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/pablovela/miniforge3/envs/xrprimer-test/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/Users/pablovela/miniforge3/envs/xrprimer-test/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/pablovela/miniforge3/envs/xrprimer-test/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/Users/pablovela/miniforge3/envs/xrprimer-test/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/Users/pablovela/miniforge3/envs/xrprimer-test/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/Users/pablovela/miniforge3/envs/xrprimer-test/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/private/var/folders/tf/rbxr_mz11n19ph5s2tzkqr580000gn/T/pip-install-jagqhs5r/xrprimer_7b2766ed18604c2ebeee1d57c104dcf5/setup.py", line 194, in build_extension
          subprocess.check_call(['cmake', '-S.', '-B', build_temp] + cmake_args)
        File "/Users/pablovela/miniforge3/envs/xrprimer-test/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '-S.', '-B', 'build/temp.macosx-11.0-arm64-cpython-310', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/tf/rbxr_mz11n19ph5s2tzkqr580000gn/T/pip-install-jagqhs5r/xrprimer_7b2766ed18604c2ebeee1d57c104dcf5/build/lib.macosx-11.0-arm64-cpython-310/', '-DPYTHON_EXECUTABLE=/Users/pablovela/miniforge3/envs/xrprimer-test/bin/python3.10', '-DCMAKE_BUILD_TYPE=Release', '-DENABLE_TEST=OFF', '-DBUILD_EXTERNAL=ON', '-DXRPRIMER_VERSION_MAJOR=0', '-DXRPRIMER_VERSION_MINOR=5', '-DXRPRIMER_VERSION_PATCH=2']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for xrprimer
  Running setup.py clean for xrprimer
Failed to build xrprimer
ERROR: Could not build wheels for xrprimer, which is required to install pyproject.toml-based p
```

**Comment by pablovela5620** [comment]
Just following up to see if there's any timeline for getting this working on MacOS

**Comment by GACLove** [comment]
> Just following up to see if there's any timeline for getting this working on MacOS

Yes, we have plans to release distribution libraries and Python packages for xrprimer on Mac and Windows around November.
    I would like to know if you intend to use xrprimer directly or if the package you are using already includes it?
    If the package you are using depends on xrprimer, could you please let us know which packages have this dependency? This information would be helpful for us in releasing the Mac version of xrprimer.

**Comment by pablovela5620** [comment]
> > Just following up to see if there's any timeline for getting this working on MacOS
> 
> Yes, we have plans to release distribution libraries and Python packages for xrprimer on Mac and Windows around November. I would like to know if you intend to use xrprimer directly or if the package you are using already includes it? If the package you are using depends on xrprimer, could you please let us know which packages have this dependency? This information would be helpful for us in releasing the Mac version of xrprimer.

This is for using xrprimer package directly! Thanks
